export default {
    authenticated: false,
    userEmail: '',
    newUrl: '',
    narucekanju: [],
    narudzbeuobradi: [],
    obrnarudzbe: [],
    imageData: null,
    ime: '',
    prezime: '',
    imep: '',
    prezimep: '',
    profil: '',
    pretraga: '',
    adminstatus: false,
    id: '',
    poslovnica: '',
    mjesto: '',
}